-- =============================================================================
-- HVAC AI Lead Intelligence Platform - Demo Leads
-- Version: 1.1.0
-- Company: Metro HVAC & Field Services
-- 5 Realistic HVAC leads with different statuses, priorities, and cities
-- =============================================================================
-- Owner IDs are NULL so leads appear as unassigned and visible to all users
-- via RLS "Users can view all leads" policy.

insert into public.hvac_leads (id, customer_name, phone, email, city, service_type, property_type, issue_description, lead_quality, urgency, estimated_job_value, customer_intent, recommended_response_time, service_category, summary, recommended_action, lead_score, priority, status, source)
values
(
    '10000000-0000-0000-0000-000000000001',
    'Arafin Azizul',
    '5551234567',
    'arafinazizul@gmail.com',
    'Dallas',
    'AC Repair',
    'Residential',
    'AC is blowing warm air and making a loud humming noise in the backyard. Unit is 8 years old, R-410A refrigerant.',
    'HIGH',
    'NORMAL',
    'MEDIUM',
    'READY_TO_BUY',
    'Within 2 Hours',
    'Cooling',
    'AC blowing warm air, outdoor unit compressor humming. Customer is ready to book.',
    'Call customer immediately to schedule diagnostic visit.',
    85,
    'HIGH',
    'NEW',
    'Website'
),
(
    '20000000-0000-0000-0000-000000000002',
    'Sarah Jenkins',
    '5559876543',
    'sjenkins@yahoo.com',
    'Houston',
    'Heater Maintenance',
    'Residential',
    'Heater is emitting a burning smell when turned on for the winter season. Customer wants a safety inspection before full winter.',
    'MEDIUM',
    'NORMAL',
    'LOW',
    'SHOPPING',
    'Within 24 Hours',
    'Heating',
    'Burning smell observed on furnace startup. Standard safety check required.',
    'Email maintenance options or follow up tomorrow morning.',
    60,
    'MEDIUM',
    'CONTACTED',
    'Google Ads'
),
(
    '30000000-0000-0000-0000-000000000003',
    'Michael Chang',
    '5554567890',
    'mchang@changlegal.com',
    'Austin',
    'Commercial HVAC Overhaul',
    'Commercial',
    'Lobby split system is completely dead, office temperature is rising rapidly. Multiple tenants complaining.',
    'HIGH',
    'EMERGENCY',
    'HIGH',
    'READY_TO_BUY',
    'Immediate (Within 30m)',
    'Cooling',
    'Commercial building lobby cooling failure. Extreme business downtime risk.',
    'Dispatch emergency commercial diagnostic technician immediately.',
    98,
    'CRITICAL',
    'SCHEDULED',
    'Phone'
),
(
    '40000000-0000-0000-0000-000000000004',
    'David Miller',
    '5553210987',
    'dmiller@hotmail.com',
    'Fort Worth',
    'Heat Pump Installation',
    'Residential',
    'Interested in replacing old inefficient 15 SEER heat pump with new energy star unit. 2000 sq ft home.',
    'HIGH',
    'LOW',
    'HIGH',
    'SHOPPING',
    'Within 48 Hours',
    'Cooling',
    'Residential heat pump installation estimate request. High value sales lead.',
    'Schedule senior comfort advisor for home heat loss calculation.',
    75,
    'MEDIUM',
    'NEW',
    'Referral'
),
(
    '50000000-0000-0000-0000-000000000005',
    'Emma Rodriguez',
    '5551112222',
    'erodriguez@outlook.com',
    'San Antonio',
    'Furnace Repair',
    'Residential',
    'Furnace will not ignite and thermostat is throwing error code 14. House temperature dropping to 55F.',
    'HIGH',
    'HIGH',
    'MEDIUM',
    'READY_TO_BUY',
    'Within 1 Hour',
    'Heating',
    'Furnace ignition lockout error code 14. Immediate cold weather risk.',
    'Call customer immediately to schedule diagnostic visit.',
    92,
    'CRITICAL',
    'NEW',
    'Facebook'
);
